version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudFormationStackHelloWorldSL"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1s3w39ulydtlq"
s3_prefix = "CloudFormationStackHelloWorldSL"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=058213536462.dkr.ecr.us-west-1.amazonaws.com/cloudformationstackhelloworldslc4e7cde6/helloworldfunction19d43fc4repo"]
